services:
  remux-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    ports:
      - "3001:3000"
    #command: ["bash", "-c", "tail -f /dev/null"]
    #command: ["bash", "-lc", "ls -la ."]
    #command: ["/app/remux-server"]